# -*- coding: utf-8 -*-
"""Logistics_regression(diabetes dataset).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FMeq4PSyOEwI4htKHIFKPk-bd4BBqeNU
"""

import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv('/content/drive/MyDrive/diabetes.csv')

df.head()

df.shape

df.describe()

df0 = df.drop('SkinThickness', axis='columns')

df0

df_x = df0.iloc[:, :-1]
df_x

df_y = df0.iloc[:, 7]
df_y

x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.25, random_state=21 )

from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(random_state=16)

LR.fit(x_train, y_train)

pred = LR.predict(x_test)

pred

pred == y_test

from sklearn import metrics

cnf = metrics.confusion_matrix(y_test, pred)

cnf
'''
  t+ , f+
  f- , t-

  t+: correct +ve values,
'''











